"""Initial migration

Revision ID: 0e69335e3250
Revises: 
Create Date: 2025-02-27 15:48:54.762120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e69335e3250'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('img_link', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('destination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('img_link', sa.String(length=200), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('months', sa.String(length=50), nullable=True),
    sa.Column('accomodation_link', sa.String(length=200), nullable=True),
    sa.Column('accomodation_price', sa.String(length=50), nullable=True),
    sa.Column('accomodation_text', sa.String(length=500), nullable=True),
    sa.Column('trip_duration', sa.String(length=50), nullable=True),
    sa.Column('trip_price', sa.String(length=50), nullable=True),
    sa.Column('trip_text', sa.String(length=500), nullable=True),
    sa.Column('free_text', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.Column('activity_text', sa.String(length=500), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('web_link', sa.String(length=200), nullable=True),
    sa.Column('img_link', sa.String(length=200), nullable=True),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('trip_duration', sa.String(length=50), nullable=True),
    sa.Column('trip_price', sa.String(length=50), nullable=True),
    sa.Column('trip_text', sa.String(length=500), nullable=True),
    sa.Column('free_text', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    op.drop_table('destination')
    op.drop_table('user')
    # ### end Alembic commands ###
